### ISSUE TITLE
2nd save button on new person page is broken

### ISSUE THREAD

**Issue by lukesands-co** [ministryofjustice/peoplefinder#251]
Hi guys,

On the [new person](https://peoplefinder.service.gov.uk/people/new) page, the save button at the bottom of the page is not working.

Looks like it is due to line 245 of [photo_upload.js](https://github.com/ministryofjustice/peoplefinder/blob/master/app/assets/javascripts/peoplefinder/photo_upload.js), which is expecting an edit form.

I think! We did a [quick fix](https://github.com/cabinetoffice/peoplefinder/blob/master/app/assets/javascripts/peoplefinder/photo_upload.js) in the CO instance.

Thanks,
Luke.

**Comment by robmckinnon** [comment]
Thanks, we've applied the fix: https://github.com/ministryofjustice/peoplefinder/pull/261
