### ISSUE TITLE
Use _html i18n keys to avoid .html_safe

### ISSUE THREAD

**Issue by threedaymonk** [ministryofjustice/peoplefinder#44]
In [application_helper.rb](https://github.com/ministryofjustice/peoplefinder/blob/d4511cfe491fe4bfbb8402ab532d8d9a5795987a/app/helpers/peoplefinder/application_helper.rb#L38), translations are marked as `html_safe` to allow them to contain markup (e.g. line breaks):

```ruby
def info_text(key)
  t(key, scope: %w[peoplefinder views info_text].join('.')).html_safe
end
```

There is a better solution; see [Using Safe HTML Translations](http://guides.rubyonrails.org/i18n.html#using-safe-html-translations):

> Keys with a '_html' suffix and keys named 'html' are marked as HTML safe. When you use them in views the HTML will not be escaped.

**Comment by Najaf** [comment]
:+1: good shout
